<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_iframe_105</name>
   <tag></tag>
   <elementGuidId>0d7c1f3d-78fd-4a40-b97e-e8a34b89093e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe_105</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./MyWork/MyWork.aspx?pid=100004&amp;aid=100027&amp;level1fieldid=0&amp;level1fieldvalue=&amp;nulllevel1fieldvalue=False&amp;level2fieldid=0&amp;level2fieldvalue=&amp;nulllevel2fieldvalue=False&amp;level3fieldid=0&amp;level3fieldvalue=&amp;nulllevel3fieldvalue=False&amp;params={&quot;NodeType&quot;:2,&quot;ProcessID&quot;:100004,&quot;PartialRefresh&quot;:false,&quot;ActivityID&quot;:100027,&quot;FolderingEditable&quot;:false,&quot;FolderLevel&quot;:0,&quot;Level1FieldID&quot;:0,&quot;Level1FieldColumnName&quot;:null,&quot;Level1FieldValue&quot;:null,&quot;NullLevel1FieldValue&quot;:false,&quot;Level2FieldID&quot;:0,&quot;Level2FieldColumnName&quot;:null,&quot;Level2FieldValue&quot;:null,&quot;NullLevel2FieldValue&quot;:false,&quot;Level3FieldID&quot;:0,&quot;Level3FieldColumnName&quot;:null,&quot;Level3FieldValue&quot;:null,&quot;NullLevel3FieldValue&quot;:false}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe_105&quot;)</value>
   </webElementProperties>
</WebElementEntity>
