<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_work_items</name>
   <tag></tag>
   <elementGuidId>a7d15cc7-6ce3-48e6-9d96-18ddd37a0a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id = '8b1776e6-13a5-497c-a0d5-34e9103a8ae7_iframe' and @ref_element = 'Object Repository/Page_Savana nGage/MyWork_Objects/iframe_iframe_105']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrkitmsholder']//div[@aria-labelledby='ui-id-1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8b1776e6-13a5-497c-a0d5-34e9103a8ae7_iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabpanel-iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>WorkItems.aspx?loc=&amp;did=&amp;revid=&amp;pid=100004&amp;tid=&amp;dtid=&amp;dcid=&amp;highlight=&amp;sdid=&amp;opm=&amp;opwm=&amp;odighaw=&amp;dwid=&amp;pdwid=&amp;aid=100027&amp;epmSTAGEDDOCUMENTID=&amp;epmSTAGEDFILETYPE=&amp;fvid=&amp;ConID=&amp;ConType=&amp;OnChngDcDt=&amp;preFilledFields=&amp;mode=&amp;level1fieldid=0&amp;level1fieldvalue=&amp;nulllevel1fieldvalue=False&amp;level2fieldid=0&amp;level2fieldvalue=&amp;nulllevel2fieldvalue=False&amp;level3fieldid=0&amp;level3fieldvalue=&amp;nulllevel3fieldvalue=False&amp;params=%7b%22NodeType%22%3a2%2c%22ProcessID%22%3a100004%2c%22PartialRefresh%22%3afalse%2c%22ActivityID%22%3a100027%2c%22FolderingEditable%22%3afalse%2c%22FolderLevel%22%3a0%2c%22Level1FieldID%22%3a0%2c%22Level1FieldColumnName%22%3anull%2c%22Level1FieldValue%22%3anull%2c%22NullLevel1FieldValue%22%3afalse%2c%22Level2FieldID%22%3a0%2c%22Level2FieldColumnName%22%3anull%2c%22Level2FieldValue%22%3anull%2c%22NullLevel2FieldValue%22%3afalse%2c%22Level3FieldID%22%3a0%2c%22Level3FieldColumnName%22%3anull%2c%22Level3FieldValue%22%3anull%2c%22NullLevel3FieldValue%22%3afalse%7d</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8b1776e6-13a5-497c-a0d5-34e9103a8ae7_iframe&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_nGage_Dashboard/My_Work/iframe_iframe_105</value>
   </webElementProperties>
</WebElementEntity>
