<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_ChildItems_CorrespondanceActivity</name>
   <tag></tag>
   <elementGuidId>131a0bc8-12ea-4fb3-8be0-3b411c8da52c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ACTIVITY_100001_100001']/ul[@class='jstree-children']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
