<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Work Items</name>
   <tag></tag>
   <elementGuidId>8ad74a3b-743a-4627-9925-1a18ad791c05</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#8b1776e6-13a5-497c-a0d5-34e9103a8ae7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabref tooltip  ui-tabs-anchor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>workItems</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-targeturl</name>
      <type>Main</type>
      <value>WorkItems.aspx?loc=&amp;did=&amp;revid=&amp;pid=100004&amp;tid=&amp;dtid=&amp;dcid=&amp;highlight=&amp;sdid=&amp;opm=&amp;opwm=&amp;odighaw=&amp;dwid=&amp;pdwid=&amp;aid=100027&amp;epmSTAGEDDOCUMENTID=&amp;epmSTAGEDFILETYPE=&amp;fvid=&amp;ConID=&amp;ConType=&amp;OnChngDcDt=&amp;preFilledFields=&amp;mode=&amp;level1fieldid=0&amp;level1fieldvalue=&amp;nulllevel1fieldvalue=False&amp;level2fieldid=0&amp;level2fieldvalue=&amp;nulllevel2fieldvalue=False&amp;level3fieldid=0&amp;level3fieldvalue=&amp;nulllevel3fieldvalue=False&amp;params=%7b%22NodeType%22%3a2%2c%22ProcessID%22%3a100004%2c%22PartialRefresh%22%3afalse%2c%22ActivityID%22%3a100027%2c%22FolderingEditable%22%3afalse%2c%22FolderLevel%22%3a0%2c%22Level1FieldID%22%3a0%2c%22Level1FieldColumnName%22%3anull%2c%22Level1FieldValue%22%3anull%2c%22NullLevel1FieldValue%22%3afalse%2c%22Level2FieldID%22%3a0%2c%22Level2FieldColumnName%22%3anull%2c%22Level2FieldValue%22%3anull%2c%22NullLevel2FieldValue%22%3afalse%2c%22Level3FieldID%22%3a0%2c%22Level3FieldColumnName%22%3anull%2c%22Level3FieldValue%22%3anull%2c%22NullLevel3FieldValue%22%3afalse%7d</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isactive</name>
      <type>Main</type>
      <value>False</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-header</name>
      <type>Main</type>
      <value>Work Items</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work Items </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-1&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_nGage_Dashboard/My_Work/iframe_iframe_105</value>
   </webElementProperties>
</WebElementEntity>
