<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>EDM</description>
   <name>Icon_Expand_SavedSearch</name>
   <tag></tag>
   <elementGuidId>8ded3fff-7c69-4bae-a5c7-175af092d6ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='SAVEDSEARCH']/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
