<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Schema</name>
   <tag></tag>
   <elementGuidId>3179333b-3c41-404e-9033-c73cb4ca6c5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'Login1$cbSchema' and @id = 'Login1_cbSchema' and (text() = '
					ALLIANCE_50
					CMDR
					DRC20160623
					EPM47MASTER_47
					HWAFISBBDCSMDEV_50
					HWAFISMUBCSMDEV
					IPM_EDF_CMS_MAINT
					IPM_EPM172MASTER_172032_QA
					IPM_EPM173MASTER_173066_QA
					IPM_EPM173MASTER_173067_QA
					IPM_EPM174MASTER_174071_QA
					IPM_EPM181MASTER_18109_QA
					IPM_EPM182MASTER_182021_QA
					IPM_EPM50MASTER_50
					IPM_EPM50MASTER_50_QA
					IPM_EPM50MASTER_502
					IPM_EPM50MASTER_502_DEV
					IPM_EPM50MASTER_502_QA
					IPM_EPM50MASTER_502_QA_TLS
					IPM_EPM50MASTER_502_QA_WITHOUTCATEGORY
					IPM_EPMMASTER_171018_QA
					IPM_EPMMASTER_171018_QA_OLD
					IPM_FNIS_50_MAINT
					IPM_FNIS_50_QA
					IPM_FNTG_365_QA
					IPM_MUB_50_QA
					IPM_NGAGECMS2_50_QA
					IPM_NGAGECMS2_HF
					IPM_NGAGECMS5_50_QA
					IPM_PHH_50_QA
					IPM_PHHDEV_50_ENH
					IPM_SERLINK_50_QA
					IPM_VAL_50_MAINT
					IPM_VAL_50_QA
					NGAGE_DEV
					NGAGECMSHP
					SAVANA
					SAVANALOSIPM

				' or . = '
					ALLIANCE_50
					CMDR
					DRC20160623
					EPM47MASTER_47
					HWAFISBBDCSMDEV_50
					HWAFISMUBCSMDEV
					IPM_EDF_CMS_MAINT
					IPM_EPM172MASTER_172032_QA
					IPM_EPM173MASTER_173066_QA
					IPM_EPM173MASTER_173067_QA
					IPM_EPM174MASTER_174071_QA
					IPM_EPM181MASTER_18109_QA
					IPM_EPM182MASTER_182021_QA
					IPM_EPM50MASTER_50
					IPM_EPM50MASTER_50_QA
					IPM_EPM50MASTER_502
					IPM_EPM50MASTER_502_DEV
					IPM_EPM50MASTER_502_QA
					IPM_EPM50MASTER_502_QA_TLS
					IPM_EPM50MASTER_502_QA_WITHOUTCATEGORY
					IPM_EPMMASTER_171018_QA
					IPM_EPMMASTER_171018_QA_OLD
					IPM_FNIS_50_MAINT
					IPM_FNIS_50_QA
					IPM_FNTG_365_QA
					IPM_MUB_50_QA
					IPM_NGAGECMS2_50_QA
					IPM_NGAGECMS2_HF
					IPM_NGAGECMS5_50_QA
					IPM_PHH_50_QA
					IPM_PHHDEV_50_ENH
					IPM_SERLINK_50_QA
					IPM_VAL_50_MAINT
					IPM_VAL_50_QA
					NGAGE_DEV
					NGAGECMSHP
					SAVANA
					SAVANALOSIPM

				')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'Login1_cbSchema']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Login1$cbSchema</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Login1_cbSchema</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginfields loginschemadrp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					ALLIANCE_50
					CMDR
					DRC20160623
					EPM47MASTER_47
					HWAFISBBDCSMDEV_50
					HWAFISMUBCSMDEV
					IPM_EDF_CMS_MAINT
					IPM_EPM172MASTER_172032_QA
					IPM_EPM173MASTER_173066_QA
					IPM_EPM173MASTER_173067_QA
					IPM_EPM174MASTER_174071_QA
					IPM_EPM181MASTER_18109_QA
					IPM_EPM182MASTER_182021_QA
					IPM_EPM50MASTER_50
					IPM_EPM50MASTER_50_QA
					IPM_EPM50MASTER_502
					IPM_EPM50MASTER_502_DEV
					IPM_EPM50MASTER_502_QA
					IPM_EPM50MASTER_502_QA_TLS
					IPM_EPM50MASTER_502_QA_WITHOUTCATEGORY
					IPM_EPMMASTER_171018_QA
					IPM_EPMMASTER_171018_QA_OLD
					IPM_FNIS_50_MAINT
					IPM_FNIS_50_QA
					IPM_FNTG_365_QA
					IPM_MUB_50_QA
					IPM_NGAGECMS2_50_QA
					IPM_NGAGECMS2_HF
					IPM_NGAGECMS5_50_QA
					IPM_PHH_50_QA
					IPM_PHHDEV_50_ENH
					IPM_SERLINK_50_QA
					IPM_VAL_50_MAINT
					IPM_VAL_50_QA
					NGAGE_DEV
					NGAGECMSHP
					SAVANA
					SAVANALOSIPM

				</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Login1_cbSchema&quot;)</value>
   </webElementProperties>
</WebElementEntity>
