<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ToolBar_2</name>
   <tag></tag>
   <elementGuidId>71194e73-3bd3-47d5-a077-a9704ff5b635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ORept_MainToolbarRowIDtb2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_nGage_Dashboard/Report/Work Items In Waiting/IFrame_Work Items In Waiting</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//tr[@id='ORept_MainToolbarRowIDtb2']</value>
   </webElementXpaths>
</WebElementEntity>
