<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PageNumber</name>
   <tag></tag>
   <elementGuidId>143c4b13-48da-42b1-bbfd-3a785a3ac556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'eform_mcb67676_TabContainer_4_TabRef_2_phBO_5_BO_grc_ctl01_PageDropDownList' and @ref_element = 'Object Repository/Page_WMI_NEW/Reference_Object_Feature/Reference_Grid_feature/tab_2)Reference grid(Page size(single page))/iframe_Close Window_ContentPla']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eform_mcb67676$TabContainer_4$TabRef_2$phBO_5_BO$grc$ctl01$PageDropDownList</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'eform_mcb67676$TabContainer_4$TabRef_2$phBO_5_BO$grc$ctl01$PageDropDownList\',\'\')', 0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eform_mcb67676_TabContainer_4_TabRef_2_phBO_5_BO_grc_ctl01_PageDropDownList</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
														1
														2
														3
														4
														5
														6
														7
														8
														9
														10
														11
														12
														13
														14
														15
														16
														17
														18
														19
														20
														21
														22
														23
														24
														25
														26
														27
														28
														29
														30
														31
														32
														33
														34
														35
														36
														37
														38
														39
														40
														41
														42
														43
														44
														45
														46
														47
														48
														49
														50
														51
														52
														53
														54
														55
														56
														57
														58
														59
														60
														61
														62
														63
														64
														65
														66
														67
														68
														69
														70
														71
														72
														73
														74
														75
														76
														77
														78
														79
														80
														81
														82
														83
														84
														85
														86
														87
														88
														89
														90
														91
														92
														93
														94
														95
														96
														97
														98
														99
														100
														101
														102
														103
														104
														105
														106
														107
														108
														109
														110
														111
														112
														113
														114
														115
														116
														117
														118
														119
														120
														121
														122
														123
														124
														125
														126
														127
														128
														129
														130
														131
														132
														133
														134
														135
														136
														137
														138
														139
														140
														141
														142
														143
														144
														145
														146
														147
														148
														149
														150
														151
														152
														153
														154
														155
														156
														157
														158
														159
														160
														161
														162
														163
														164
														165
														166
														167
														168
														169
														170
														171
														172
														173
														174
														175
														176
														177
														178
														179
														180
														181
														182
														183
														184

													</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eform_mcb67676_TabContainer_4_TabRef_2_phBO_5_BO_grc_ctl01_PageDropDownList&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_WMI_NEW/Reference_Object_Feature/Reference_Grid_feature/tab_2)Reference grid(Page size(single page))/iframe_Close Window_ContentPla</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='eform_mcb67676_TabContainer_4_TabRef_2_phBO_5_BO_grc_ctl01_PageDropDownList']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='eform_mcb67676_TabContainer_4_TabRef_2_phBO_5_BO_grc_ctl01_pagerDiv']/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Duplicate values will be ignored.'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 184'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[2]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/table/tbody/tr/td/div[2]/div/fieldset/table/tbody/tr[3]/td/div[2]/div/table/tbody/tr/td/table/tbody/tr/td/div[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
