<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EDM_WMI005_Chintan_RenderAllFields_SubMenu</name>
   <tag></tag>
   <elementGuidId>5bbb1a1c-3ab6-497f-bcba-4ed56d6059ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='SCF_1ad44309-e2ca-4adc-a17c-b469c244b809_anchor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
