<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EDM_Chintan_BusinessModel_RenderAllSubMenu</name>
   <tag></tag>
   <elementGuidId>2ce540a6-18bd-4f29-b504-f1e96599d567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='SCF_10ec91ee-c8e0-4f0d-a7ad-3c717c5d3f18_anchor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
