<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EDM_RenderAllFields_BusinessModel_SubMenu</name>
   <tag></tag>
   <elementGuidId>920a3c76-a03d-43aa-ad59-86cb1d29b2cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='SCF_1a12033d-1746-404c-a037-4563b5b7cd11_anchor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
