<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EDM_08-10-2018_08Date_Empty_WMI005_BusienssModel</name>
   <tag></tag>
   <elementGuidId>ffa05334-351a-44dd-a377-f176149ab159</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='SCF_97e7d036-7431-45a3-8322-a96af441fa9a_anchor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
