<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EDM_08-13-2018_08Date_Date_WMI005_BusinessModel</name>
   <tag></tag>
   <elementGuidId>4dff7e21-3e23-4392-836d-1e725f24acd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='SCF_bd892f09-f378-4fc8-9217-086a7f326efa_anchor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
