<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_btnSearch</name>
   <tag></tag>
   <elementGuidId>e4f93621-93b4-4d77-922d-0d6f672fc348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'btnSearch' and @ref_element = 'Object Repository/Page_Savana nGage/MyWorkSimplified_Objects/iframe_iframe_110New']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSearch</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (ui.common.compareDateTime(document.getElementById('-104_1'),document.getElementById('-104_2'),'MM-dd-yyyy','Doc Stored Date') == false) return false; if (ui.common.compareDateTime(document.getElementById('100182_1'),document.getElementById('100182_2'),'MM-dd-yyyy','AI Date Fld') == false) return false; if (ui.common.compareDateTime(document.getElementById('-116_1'),document.getElementById('-116_2'),'MM-dd-yyyy hh:mm:ss tt','Doc Create Date') == false) return false; if (ui.common.compareDateTime(document.getElementById('100096_1'),document.getElementById('100096_2'),'MM-dd-yyyy hh:mm:ss tt','Process Due Date') == false) return false; if (ui.common.compareDateTime(document.getElementById('100095_1'),document.getElementById('100095_2'),'MM-dd-yyyy','Process Goal Date') == false) return false; ;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSearch</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>suite-button ui-button ui-widget ui-state-default ui-corner-all ui-state-hover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSearch&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_nGage_Dashboard/My_Work_Simplified/iframe_iframe_110</value>
   </webElementProperties>
</WebElementEntity>
