<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Dashboard</name>
   <tag></tag>
   <elementGuidId>241c1e26-f8a9-448a-83c3-a88fe552d145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrkitmsholder']//div[@aria-labelledby='ui-id-2']/iframe</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id = '9bab594d-f3de-4592-9dab-582b65a24067_iframe' and @ref_element = 'Object Repository/Page_Savana nGage/MyWork_Objects/TAB_Dashboard_Obj/iframe_iframe_105']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9bab594d-f3de-4592-9dab-582b65a24067_iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabpanel-iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>BAMActivityDashboard.aspx?loc=&amp;did=&amp;revid=&amp;pid=100002&amp;tid=&amp;dtid=&amp;dcid=&amp;highlight=&amp;sdid=&amp;opm=&amp;opwm=&amp;odighaw=&amp;dwid=&amp;pdwid=&amp;aid=100008&amp;epmSTAGEDDOCUMENTID=&amp;epmSTAGEDFILETYPE=&amp;fvid=&amp;ConID=&amp;ConType=&amp;OnChngDcDt=&amp;preFilledFields=&amp;mode=&amp;level1fieldid=100091&amp;level1fieldvalue=&amp;nulllevel1fieldvalue=False&amp;level2fieldid=-206&amp;level2fieldvalue=&amp;nulllevel2fieldvalue=False&amp;level3fieldid=0&amp;level3fieldvalue=&amp;nulllevel3fieldvalue=False&amp;params=%7b%22NodeType%22%3a2%2c%22ProcessID%22%3a100002%2c%22PartialRefresh%22%3afalse%2c%22ActivityID%22%3a100008%2c%22FolderingEditable%22%3atrue%2c%22FolderLevel%22%3a0%2c%22Level1FieldID%22%3a100091%2c%22Level1FieldColumnName%22%3anull%2c%22Level1FieldValue%22%3anull%2c%22NullLevel1FieldValue%22%3afalse%2c%22Level2FieldID%22%3a-206%2c%22Level2FieldColumnName%22%3anull%2c%22Level2FieldValue%22%3anull%2c%22NullLevel2FieldValue%22%3afalse%2c%22Level3FieldID%22%3a0%2c%22Level3FieldColumnName%22%3anull%2c%22Level3FieldValue%22%3anull%2c%22NullLevel3FieldValue%22%3afalse%7d</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9bab594d-f3de-4592-9dab-582b65a24067_iframe&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_nGage_Dashboard/My_Work/TAB_Dashboard_Obj/iframe_iframe_105</value>
   </webElementProperties>
</WebElementEntity>
